### ISSUE TITLE
Document creation race not always handled

### ISSUE THREAD

**Issue by maxg** [maxg/constellation#50]
```
org.eclipse.swt.SWTException: Failed to execute runnable (<eval>:14:39 ShareDBError: Document alredy created)
Caused by: <eval>:14:39 ShareDBError: Document alredy created
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.captureStackTrace(NativeError.java:150)
	at jdk.nashorn.internal.scripts.Script$Recompilation$100$9735A$\^eval\_.L:304#BaseError(<eval>:366)
	at jdk.nashorn.internal.scripts.Script$Recompilation$99$100925IA$\^eval\_.L:3356#ShareDBError(<eval>:3360)
	at jdk.nashorn.internal.scripts.Script$Recompilation$98$78019AA$\^eval\_.L:2220#L:2221#transformX(<eval>:2682)
	at jdk.nashorn.internal.scripts.Script$Recompilation$97$72481AA$\^eval\_.L:2220#L:2221#_handleOp(<eval>:2532)
	at jdk.nashorn.internal.scripts.Script$Recompilation$52$50490A$\^eval\_.L:1638#L:1639#handleMessage(<eval>:1874)
	at jdk.nashorn.internal.scripts.Script$Recompilation$39$48594A$\^eval\_.L:1638#L:1639#bindToSocket#onmessage(<eval>:1756)
	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source)
	at constellation.Util.callIfNotNull(Util.java:44)
	at constellation.JSWebSocket.lambda$1(JSWebSocket.java:88)
	at constellation.JSEngine.lambda$2(JSEngine.java:77)
```
and
```
org.eclipse.swt.SWTException: Failed to execute runnable (<eval>:14:39 Error: Document was created remotely)
Caused by: <eval>:14:39 Error: Document was created remotely
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110)
	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)
	at jdk.nashorn.internal.scripts.Script$Recompilation$52$50490A$\^eval\_.L:1638#L:1639#handleMessage(<eval>:1803)
	at jdk.nashorn.internal.scripts.Script$Recompilation$39$48594A$\^eval\_.L:1638#L:1639#bindToSocket#onmessage(<eval>:1756)
	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source)
	at constellation.Util.callIfNotNull(Util.java:44)
	at constellation.JSWebSocket.lambda$1(JSWebSocket.java:88)
	at constellation.JSEngine.lambda$2(JSEngine.java:77)
```

**Comment by maxg** [comment]
Shorter:
```
<eval>:14:39 ShareDBError: Document alredy created
	at \^eval\_.L:304#BaseError(<eval>:366)
	at \^eval\_.L:3356#ShareDBError(<eval>:3360)
	at \^eval\_.L:2220#L:2221#transformX(<eval>:2682)
	at \^eval\_.L:2220#L:2221#_handleOp(<eval>:2532)
	at \^eval\_.L:1638#L:1639#handleMessage(<eval>:1874)
	at \^eval\_.L:1638#L:1639#bindToSocket#onmessage(<eval>:1756)
	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept
	at constellation.Util.callIfNotNull(Util.java:44)
	at constellation.JSWebSocket.lambda$1(JSWebSocket.java:88)
	at constellation.JSEngine.lambda$2(JSEngine.java:77)
```
and
```
<eval>:14:39 Error: Document was created remotely
	at \^eval\_.L:1638#L:1639#handleMessage(<eval>:1803)
	at \^eval\_.L:1638#L:1639#bindToSocket#onmessage(<eval>:1756)
	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept
	at constellation.Util.callIfNotNull(Util.java:44)
	at constellation.JSWebSocket.lambda$1(JSWebSocket.java:88)
	at constellation.JSEngine.lambda$2(JSEngine.java:77)
```

**Comment by maxg** [comment]
Note: this is not #44.
